_wandb:
    value:
        cli_version: 0.23.1
        e:
            z6kq5xjou9vtearr4ksxn2v83c9w2taw:
                cpu_count: 18
                cpu_count_logical: 18
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "549755813888"
                        used: "12730368"
                email: lihanc@berkeley.edu
                executable: /.uv/.venv/bin/python
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-1764de79-22a7-a1b2-8474-9d4bdd090bdc
                host: modal
                memory:
                    total: "404806692864"
                os: Linux-4.4.0-x86_64-with-glibc2.36
                program: -m modal._container_entrypoint
                python: CPython 3.11.12
                root: /vol/wandb
                startedAt: "2026-02-02T00:47:18.394522Z"
                writerId: z6kq5xjou9vtearr4ksxn2v83c9w2taw
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 128
chunk_size:
    value: 8
data_dir:
    value: /vol/data
eval_interval:
    value: 10000
exp_name:
    value: null
flow_num_steps:
    value: 10
hidden_dims:
    value:
        - 256
        - 256
        - 256
log_interval:
    value: 100
lr:
    value: 0.0003
num_epochs:
    value: 200
num_video_episodes:
    value: 5
policy_type:
    value: flow
seed:
    value: 42
video_size:
    value:
        - 256
        - 256
wandb_project:
    value: hw1-imitation
weight_decay:
    value: 0
